package com.example;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LIVE".
 */
public class live {

    private Long id;
    /** Not-null value. */
    private String column;
    /** Not-null value. */
    private String resouse;

    public live() {
    }

    public live(Long id) {
        this.id = id;
    }

    public live(Long id, String column, String resouse) {
        this.id = id;
        this.column = column;
        this.resouse = resouse;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getColumn() {
        return column;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setColumn(String column) {
        this.column = column;
    }

    /** Not-null value. */
    public String getResouse() {
        return resouse;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setResouse(String resouse) {
        this.resouse = resouse;
    }

}
