package com.example;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String userName;
    private String passWord;
    private String age;
    /** Not-null value. */
    private String cool;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String userName, String passWord, String age, String cool) {
        this.id = id;
        this.userName = userName;
        this.passWord = passWord;
        this.age = age;
        this.cool = cool;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassWord() {
        return passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    /** Not-null value. */
    public String getCool() {
        return cool;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCool(String cool) {
        this.cool = cool;
    }

}
